### ISSUE TITLE
No function clause matcing in Argon2_type/1

### ISSUE THREAD

**Issue by rawkode** [riverrun/argon2_elixir#10]
Hi,

I don't get this error in development, only in production.
```
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Argon2.argon2_type/1
        (argon2_elixir) lib/argon2.ex:169: Argon2.argon2_type("$somehash")
        (argon2_elixir) lib/argon2.ex:100: Argon2.verify_pass/2
```

I've done some Googling to see it's an issue with distillery, but I don't believe so. I've checked my production Docker image and I can see:

```
root@api-service-deployment-797861355-zq1x7:/api# ls lib/argon2_elixir-1.2.7/*
lib/argon2_elixir-1.2.7/ebin:
Elixir.Argon2.Base.beam  Elixir.Argon2.Stats.beam  Elixir.Argon2.beam  argon2_elixir.app

lib/argon2_elixir-1.2.7/priv:
argon2_nif.so
```

So the nif is deployed. Do you have any ideas that could help me out?

Thanks,
David

**Comment by rawkode** [comment]
I build and run the code in the same Docker image, so I do not believe this is disparity between build/runtime.

**Comment by riverrun** [comment]
Thanks for letting me know. I'll look into it and get back to you soon.

**Comment by riverrun** [comment]
Could you tell me how you are calling Argon2.verify_pass? The argument to argon2_type should be a string starting with "argon2".

**Comment by rawkode** [comment]
Hi @riverrun,

I'm using `:comeonin`, so it looks like this:

```elixir
alias Comeonin.Argon2, as: PasswordHasher
PasswordHasher.checkpw(password, password_hash)
```

**Comment by riverrun** [comment]
And does the password_hash start with "$argon2d", "$argon2i", "$argon2id", or none of these these three?

**Comment by rawkode** [comment]
It starts with `$2b$12`

**Comment by rawkode** [comment]
We hash with `PasswordHasher.hashpwsalt(password)`

**Comment by riverrun** [comment]
I understand now. That's a bcrypt hash. You need to verify it with `Comeonin.Bcrypt.checkpw`. I think you need to check the alias you are using when you call `PasswordHasher.hashpwsalt(password)`. You need to use the same algorithm for hashing and verifying.

**Comment by rawkode** [comment]
@riverrun You're right, sorry! There's a single bcrypt hash in the Elasticsearch index, as the rest say argon.

Sorry about that

**Comment by riverrun** [comment]
No worries. I'm glad you got it fixed.
