### ISSUE TITLE
Re: documentation.  Recommended production configuration

### ISSUE THREAD

**Issue by thirdreplicator** [riverrun/argon2_elixir#11]
Hello!
  The recommended configuration parameters for the TEST are given in the documentation.  What are the recommended PRODUCTION configuration parameters?  Can you give examples/insight into reasoning about possible tweaks to the parameters? 
  Also, re: a production set up: Since the algorithm is designed to consume a lot of memory and CPU, would it be better to have a separate authentication server to handle the case of a fast growing app?  I noticed that it takes about 0.25 seconds on to do the hash, so assuming CPU (and not memory would be the bottle neck) 4 user registrations per second would use up a whole CPU.  How should we estimate RAM usage too?
  Thanks a lot for your insight.  BTW, I'm happy to update the documentation if you think it would be helpful on these points.
  Regards,
  D :)

**Comment by riverrun** [comment]
The information about production values is in the Argon2.Stats module documentation. I have updated the README and the Argon2.Base.hash_password docs to make it clearer where you can find this information.

About CPU usage, all I can suggest is that you monitor how often people login and try to work out from that information if you need to add more cores to handle this. A lot can also depend on how often you make users login to your app.

If you have any further comment / questions, just let me know.
