### ISSUE TITLE
windows make issues...

### ISSUE THREAD

**Issue by tensor-programming** [riverrun/argon2_elixir#14]
Hi, 

I had some issues with building the library on windows.  I looked at the issues that have been closed already and one of them mention that the issue that I seem to be encountering should have been fixed.  The error message is this: 

```c_src\argon2_nif.c(56): warning C4133: 'function': incompatible types - from 'argon2_type *' to 'unsigned int *'
c_src\argon2_nif.c(112): error C2036: 'void *': unknown size
c_src\argon2_nif.c(147): warning C4133: 'function': incompatible types - from 'argon2_type *' to 'unsigned int *'
c_src\argon2_nif.c(177): warning C4133: 'function': incompatible types - from 'argon2_type *' to 'unsigned int *'

Generating Code...
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.EXE"' : return code '0x2'
Stop.
```

As I mentioned before, one of the other issues mentioned something about changing the c file to work with LVA (This one specifically: https://github.com/riverrun/argon2_elixir/issues/6). It also mentioned something about how the compiler couldn't properly read the syntax etc.  The type errors I see from my error code seem to be fewer then the older issue but all but 1 of them are common it seems.  I tried to override the version by downloading the git version directly but that didn't get the c files it seems.  I also tried building the libraries directly by going into the folder and using `nmake /F makefile.win all` but that didn't seem to give me a different outcome.

Do you have any suggestions?

**Comment by riverrun** [comment]
I'll look at the incompatible types error. The VLA issue has already been solved.

**Comment by riverrun** [comment]
I have just updated the hex package to 1.2.12. In that update, I added explicit casts from int to enum and changed the type of hash to char *, and I think that should deal with the errors you are seeing. Let me know if that works.

**Comment by tensor-programming** [comment]
Alright Ill give it a shot and see what happens.  Thank you.

**Comment by riverrun** [comment]
Great!

Thanks for reporting the issue.
