### ISSUE TITLE
Upgrading from v1.2.9 to v1.2.12 breaks `hashpwsalt` under some circumstanctes

### ISSUE THREAD

**Issue by rohit-lshift** [riverrun/argon2_elixir#15]
Firstly thanks for the lib. It's great along with your other open source work.

I just upgraded this library to `v1.2.12` and `Comeonin.Argon2.hashpwsalt` function under some circumstances is returning values like `{<<184>>, "$argon2i$v=19$m=256,t=1,p=1$iabL0itQRUH/Ock+gk6dmQ$OmqPbEWpE+ay6WIeW9LxCtym2ue29UAgVKKWIqbk2+s", {1, 8, 1, 0, true, 32, 1}` instead of a string.

But when I run the same function with the same input in a repl session, I get back a string.

This behaviour is obviously very strange. Any help on this would be appreciated.

Thanks

**Comment by riverrun** [comment]
What is the command when you get this strange output? Is it in your tests?

**Comment by rohit-lshift** [comment]
It is in the tests. I ran my tests to see if everything is ok but some of my tests started failing.

**Comment by riverrun** [comment]
Ok. I'll have a fix soon.

**Comment by rohit-lshift** [comment]
Cheers!

**Comment by riverrun** [comment]
1.2.13 has a fix - I hope :)

**Comment by rohit-lshift** [comment]
Its fixed. Thanks!
