### ISSUE TITLE
Build issues on Windows

### ISSUE THREAD

**Issue by DKhalil** [riverrun/argon2_elixir#16]
We're running into build issues on Windows (https://github.com/Brainsware/sealas/issues/12) with the appveyor CI.
The full log is here:
https://ci.appveyor.com/project/Brainsware/sealas/build/1.0.74

It actually builds

```

==> argon2_elixir
Microsoft (R) Program Maintenance Utility Version 14.11.25547.0
Copyright (C) Microsoft Corporation.  All rights reserved.
	erl -eval "io:format(\"~s~n\", [lists:concat([\"ERTS_INCLUDE_PATH=\", code:root_dir(), \"/erts-\", erlang:system_info(version), \"/include\"])])" -s init stop -noshell > Makefile.auto.win
	nmake /                   /F Makefile.win priv\argon2_nif.dll
Microsoft (R) Program Maintenance Utility Version 14.11.25547.0
Copyright (C) Microsoft Corporation.  All rights reserved.
'priv\argon2_nif.dll' is up-to-date
Compiling 3 files (.ex)
Generated argon2_elixir app
```

but then when it's being loaded it fails with the following error:

```
...07:26:38.773 [error] Process #PID<0.5627.0> raised an exception
** (RuntimeError) An error occurred when loading Argon2.
Make sure you have a C compiler and Erlang 20 installed.
If you are not using Erlang 20, either upgrade to Erlang 20 or
use bcrypt_elixir (version 0.12) or pbkdf2_elixir.
See the Comeonin wiki for more information.
    (argon2_elixir) lib/argon2/base.ex:16: Argon2.Base.init/0
    (kernel) code_server.erl:1347: anonymous fn/1 in :code_server.handle_on_load/5
07:26:38.773 [warn] The on_load function for module Elixir.Argon2.Base returned {%RuntimeError{message: "An error occurred when loading Argon2.\nMake sure you have a C compiler and Erlang 20 installed.\nIf you are not using Erlang 20, either upgrade to Erlang 20 or\nuse bcrypt_elixir (version 0.12) or pbkdf2_elixir.\nSee the Comeonin wiki for more information.\n"},
 [{Argon2.Base, :init, 0, [file: 'lib/argon2/base.ex', line: 16]},
  {:code_server, :"-handle_on_load/5-fun-0-", 1,
   [file: 'code_server.erl', line: 1347]}]}
  1) test registration register with an existing email (SealasSso.RegistrationControllerTest)
     test/sealas_sso/controllers/registration_controller_test.exs:20
     ** (UndefinedFunctionError) function Argon2.Base.hash_password/3 is undefined (module Argon2.Base is not available)
     code: |> User.create_test_changeset(@create_attrs)
     stacktrace:
       (argon2_elixir) Argon2.Base.hash_password("some password", <<243, 123, 130, 7, 67, 238, 196, 60, 221, 18, 6, 156, 0, 102, 142, 152>>, [])
       (sealas_sso) lib/sealas_sso/types/hashedpassword.ex:7: EctoHashedPassword.cast/1
       (ecto) lib/ecto/changeset.ex:509: Ecto.Changeset.cast_field/8
       (ecto) lib/ecto/changeset.ex:472: Ecto.Changeset.process_param/7
       (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/changeset.ex:449: Ecto.Changeset.cast/6
       test/sealas_sso/controllers/registration_controller_test.exs:22: (test)
```

**Comment by Aridjar** [comment]
Also working on Windows, I got a similar problem about the Makefile. This post (at least the two last messages) helped me : https://github.com/riverrun/comeonin/issues/120#issuecomment-336847981
I got a new error now, but at least it compiles and Comeonin works.

**Comment by riverrun** [comment]
For this issue, make sure you are using version 1.2.13.

**Comment by DKhalil** [comment]
That is the version that's used (but I also fixated it now in the mix file)

```
* Getting argon2_elixir (Hex package)
  Checking package (https://repo.hex.pm/tarballs/argon2_elixir-1.2.13.tar)
```

**Comment by riverrun** [comment]
Ok. Does this issue only happen when using CI?

**Comment by DKhalil** [comment]
Yes, on my local machine (Win10x64) it works fine

**Comment by riverrun** [comment]
I have made a couple of changes to the Makefile.win file in version 1.2.14.

Could you try it out and let me know if that works?

**Comment by DKhalil** [comment]
Sadly still the same: https://ci.appveyor.com/project/Brainsware/sealas/build/1.0.98

**Comment by riverrun** [comment]
Ok. Thanks for letting me know. I'll have a closer look at the output and get back to you soon.

**Comment by riverrun** [comment]
I see you are using mingw to build the dll file. Is that what you are using on your local machine?

**Comment by DKhalil** [comment]
No, I'm not, but we're also not using mingw to build anything on the CI. It was just included from a previous iteration. Took it out now (didn't change anything). We're using VS2015.

**Comment by riverrun** [comment]
If you are running the tests async, can you try running it without async?

**Comment by DKhalil** [comment]
As far as I can see async is disabled by default - so it's disabled in our testsuite.

**Comment by riverrun** [comment]
Ok. I'll have another look at the log and see if anything stands out.

**Comment by riverrun** [comment]
Could you check that the `vcvarsall.bat` command is being run correctly?

Also, [this issue](https://github.com/riverrun/comeonin/issues/110) might have some information related to the problems you are having.

**Comment by DKhalil** [comment]
Running `file` on those files reveals that the architecture is probably correct:

```
file deps\argon2_elixir\priv\argon2_nif.dll
deps\argon2_elixir\priv\argon2_nif.dll: PE32+ executable (DLL) (GUI) x86-64, for MS Windows
file "c:\program files/erl9.0/erts-9.0/bin/erl.exe"
c:\program files/erl9.0/erts-9.0/bin/erl.exe: PE32+ executable (console) x86-64, for MS Windows
```

Just to be safe I'm executing vcvarsall before every stage of the build process. Sadly, no change

**Comment by riverrun** [comment]
I'm afraid to say I don't know what to suggest next :(

Just to clarify the situation, the `on_load` errors are normally caused by one of the following:

* the so / dll file cannot be found
* there is a version mismatch between the version of Erlang that built the so / dll and the version that is running it
* (with Windows) the environment variables are not correctly set
* (with argon2_elixir) lack of support for dirty schedulers (Erlang 20 supports them by default, so that does not appear to be the problem here)

Maybe you can contact the CI provider and see if they have any suggestions about how to solve this problem.

**Comment by DKhalil** [comment]
Will do that - thanks for the help!

One thing that I just noticed, when looking at the erlang versions: the build process seems to include "c:/Program Files/erl8.3/erts-8.3/include", not erl9.0. Could that be/do anything? How would I check for differences in erlang versions building and running the code?

**Comment by DKhalil** [comment]
OH GOD YES!
That was it. Erlang 19.3 was pre-installed by appveyor and got used to compile the DLL.
Removed it:
- SET PATH=%PATH:C:\Program Files\erl8.3\bin;=%
And then went on to install Erlang 20 as usual.

Now it works!

**Comment by riverrun** [comment]
Great to hear you got it fixed.

**Comment by izimbra** [comment]
@DKhalil, just want to give a big thanks for [this comment](https://github.com/riverrun/argon2_elixir/issues/16#issuecomment-351982865)!
