### ISSUE TITLE
How to use argon2id (usage example) ?

### ISSUE THREAD

**Issue by nelsonic** [riverrun/argon2_elixir#17]
Hi @riverrun, thanks for making this package! 

> Quick question: how can we use `argon2id` to `hash_password` ?

from `/lib/argon2.ex`:
https://github.com/riverrun/argon2_elixir/blob/91a911eb1197528689e47d76580c06ddfeb207d3/lib/argon2.ex#L176
it's apparent that it's _possible_ to use the `argon2id` but there is no _usage_ example in the docs (readme) or in the tests [`/test/argon2_test.exs`](https://github.com/riverrun/argon2_elixir/blob/91a911eb1197528689e47d76580c06ddfeb207d3/test/argon2_test.exs)

I _tried_ to add the following lines to `config.exs`:
```ex
config :argon2_elixir,
  argon2_type: 2
```

> I'm _keen_ to use `argon2id` because of:
https://crypto.stackexchange.com/questions/48935/why-use-argon2i-or-argon2d-if-argon2id-exists

**Comment by nelsonic** [comment]
invoking the `hash_password` function with the following format:
```elixir
Argon2.Base.hash_password("password", "salt", [{:argon2_type, 2}])
```
Appears to work.

**Comment by riverrun** [comment]
Hi. Thanks for raising the issue. I can have a look at this later this week - I'll probably update the docs, and you suggested.

**Comment by riverrun** [comment]
#18 allows you to set the argon2 type in the config, but I do also need to update the docs - which I will do soon.
