### ISSUE TITLE
What is the default t_cost and m_cost?

### ISSUE THREAD

**Issue by salman-ca** [riverrun/argon2_elixir#26]
I am wondering what the default t_cost and m_cost is for a call like:
```
Comeonin.Argon2.add_hash("hello12") 
```

I tried to look it up in the source but came up empty.  On my laptop the call above takes a while, just curious what a reasonable t/m cost is?

**Comment by riverrun** [comment]
At the moment, the default t_cost is 6, and the default m_cost is 16 (64 MiB). However, these will change in version 2.0, based on the latest Argon2 recommendations. For more information and updates, see #24.

**Comment by riverrun** [comment]
One more thing - for tests, you can use t_cost 1 and m_cost 8 - then the hashing function will run quickly.
