### ISSUE TITLE
[BUG] v2.0 not compiling on CentOS7

### ISSUE THREAD

**Issue by garretttaco** [riverrun/argon2_elixir#29]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
Erlang/OTP 21 [erts-10.2.2] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]
Elixir 1.8.0 (compiled with Erlang/OTP 20)
* Operating system: CentOS Linux release 7.6.1810

### Current behavior
Upgrading to Argon2_elixir v2.0 causes error on compilation.
```
==> argon2_elixir
could not compile dependency :argon2_elixir, "mix compile" failed. You can recompile this dependency with "mix deps.compile argon2_elixir", update it with "mix deps.update argon2_elixir" or clean it with "mix deps.clean argon2_elixir"
** (MatchError) no match of right hand side value: []
    lib/mix/tasks/compile.make.ex:247: Mix.Tasks.Compile.ElixirMake.default_env/2
    lib/mix/tasks/compile.make.ex:146: Mix.Tasks.Compile.ElixirMake.build/2
    lib/mix/tasks/compile.make.ex:119: Mix.Tasks.Compile.ElixirMake.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:68: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:52: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:23: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:39: Mix.Tasks.Compile.All.with_logger_app/1
```
I also tried mix's suggestions of cleaning and updating. It is still failing.
### Expected behavior
It just works the same as v1.x, as long as I update the function names.

### Additional information
I also followed the requirements page and made sure I have the C library development tools installed for my distro. This was compiling for me before, so not sure what changed in this version bump that would affect compilation.

**Comment by riverrun** [comment]
Thanks for letting me know. I will get back to asap.

**Comment by riverrun** [comment]
Could you try `rm -rf _build` and see if that makes any difference?

**Comment by riverrun** [comment]
It seems that a function in elixir_make is returning an empty list, and that is resulting in an error.

Please let me know what line 247 is in `deps/elixir_make/lib/mix/tasks/compile.make.ex`.

**Comment by riverrun** [comment]
And how did you install erlang - from the erang-solutions download page or from the CentOS repository?

**Comment by garretttaco** [comment]
I tried removing the `_build` directory and then recompiling. That yielded the same error. 
The code surrounding line 247 in `deps/elixir_make/lib/mix/tasks/compile.make.ex` is 
```
 # Returns a map of default environment variables
  # Defauts may be overwritten.
  defp default_env(config, default_env) do
    root_dir = :code.root_dir()
    erl_interface_dir = Path.join(root_dir, "usr")
    [erts_dir] = Path.wildcard(Path.join(root_dir, "erts*")) <----Line 247
    erts_include_dir = Path.join(erts_dir, "include")
    erl_ei_lib_dir = Path.join(erl_interface_dir, "lib")
    erl_ei_include_dir = Path.join(erl_interface_dir, "include")
```

I installed erlang from the version manager, [asdf](https://github.com/asdf-vm/asdf).

**Comment by garretttaco** [comment]
I tried removing my elixir and erlang dependencies, [following this guide](https://www.unixmen.com/install-erlang-elixir-centos-7/) as well to make sure all my prerequisites were in place for erlang, then removed the _build and deps directories and reinstalled and compiled. I still got the same error. It appears the issue is that my install with asdf does not have a file containing `erts` so its returning an empty array which is failing the pattern match. 
I reverted to the previous versions I was on for comeonin and argon2_elixir, by running `mix deps.get` and then `mix deps.compile` and it compiled just fine.
I am not sure what the difference is in the library since the previous versions, but it appears that, at least on my system, something at compile time, is attempting to reference some new low level functionality.
Not sure if you have anymore insight, but it appears like I will have to remain on the previous version until this is resolved.

**Comment by riverrun** [comment]
I have opened an issue about this at [elixir_make](https://github.com/elixir-lang/elixir_make/issues/29).

**Comment by josevalim** [comment]
Can you please run `mix deps.update elixir_make` and let us know if it fixes the issue?

**Comment by garretttaco** [comment]
I cloned this project, updated the elixir_make dependency to the latest version (0.5.1). I ran `mix deps.get` and `mix deps.compile`. 
I verified the version of elixir_make by running `mix deps.tree`. The output of which is 
```
$ mix deps.tree
argon2_elixir
├── comeonin ~> 5.0 (Hex package)
├── elixir_make ~> 0.5.1 (Hex package)
└── ex_doc ~> 0.19 (Hex package)
    ├── earmark ~> 1.2 (Hex package)
    └── makeup_elixir ~> 0.10 (Hex package)
        └── makeup ~> 0.8 (Hex package)
            └── nimble_parsec ~> 0.5.0 (Hex package)
```
I then ran `mix test` to verify that all is good before testing on my project and I get the same output. 
```
$ mix test
** (MatchError) no match of right hand side value: []
    lib/mix/tasks/compile.make.ex:247: Mix.Tasks.Compile.ElixirMake.default_env/2
    lib/mix/tasks/compile.make.ex:146: Mix.Tasks.Compile.ElixirMake.build/2
    lib/mix/tasks/compile.make.ex:119: Mix.Tasks.Compile.ElixirMake.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:68: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:52: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:23: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:39: Mix.Tasks.Compile.All.with_logger_app/1
```

**Comment by josevalim** [comment]
Thanks! I have released v0.5.2, can you please give it a try?

**Comment by garretttaco** [comment]
@josevalim Thank you for the time and effort to fix this issue. Upgrading to v0.5.2 did solve that specific error. 

@riverrun I still was getting an error on running mix test on the clone repo.
```
$ mix test
==> comeonin
Compiling 3 files (.ex)
Generated comeonin app
==> elixir_make
Compiling 1 file (.ex)
Generated elixir_make app
==> argon2_elixir
make: *** No rule to make target `argon2/src/argon2.c', needed by `priv/argon2_nif.so'.  Stop.
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. If you are using
Ubuntu or any other Debian-based system, install the packages
"build-essential". Also install "erlang-dev" package if not
included in your Erlang/OTP version. If you're on Fedora, run
"dnf group install 'Development Tools'".
```

I decided that this may just be an issue with how I installed erlang (from asdf) and instead decided to build from source to use on my project. With the current release of this project, it appears all is working on my end.
 
Not to self, apparently asdf erlang has some issues being able to access the system level install of the C "Development Tools". 

Thank you for this library and your speedy/effective help solving this issue!

**Comment by garretttaco** [comment]
I am going to close this, since the fix for this specific issue was addressed in `elixir_make` but the overall problem appeared to be my erlang version, the whole time, being compiled using asdf.

**Comment by riverrun** [comment]
If you have any further issues, please let me know.
