### ISSUE TITLE
Is release 2.1.1 legit?

### ISSUE THREAD

**Issue by mikl** [riverrun/argon2_elixir#35]
Hi there,

This might sound a bit paranoid, but I noticed that there’s a version 2.1.1 in Hex that does not appear here.

It might be completely innocent, but we’ve seen a few cases of Rubygems being hacked and packages with malicious code published, that followed this pattern (releases showing up as Gems, without appearing on Github), so I just wanted to check if everything was above board with 2.1.1.

Sorry for the inconvenience.

**Comment by riverrun** [comment]
Don't panic! Version 2.1.1 is ok.

I was working on updates to the Makefiles on a separate branch, and I forgot to merge to master before pushing the changes to hex.

Sorry about any confusion caused - I will try to make things a little clearer in the future (keeping master up-to-date).
