### ISSUE TITLE
Can't compile argon2_elixir under OS X

### ISSUE THREAD

**Issue by oscar-lopez** [riverrun/argon2_elixir#4]
I need your help, I tried compiling `argon2_elixir` under Mac OS X, without success. I tried directly compiling the C [argon2](https://github.com/P-H-C/phc-winner-argon2) reference implementation on my computer, and it worked without problems. The error reported on my Mac when compiling `argon2_elixir` is:

```bash
$ mix deps.compile argon2_elixir
==> argon2_elixir
mkdir -p priv
cc -std=c89 -pthread -O3 -Wall -g -Iargon2/include -Iargon2/src -Ic_src -I/usr/local/Cellar/erlang/19.1/lib/erlang/erts-8.1/include -march=native -dynamiclib -install_name @rpath/libpriv/argon2_nif.dylib   argon2/src/argon2.c argon2/src/core.c argon2/src/blake2/blake2b.c argon2/src/thread.c argon2/src/encoding.c c_src/argon2_nif.c argon2/src/opt.c -o priv/argon2_nif.dylib
Undefined symbols for architecture x86_64:
  "_enif_get_int", referenced from:
      _argon2_error_nif in argon2_nif-16ff57.o
  "_enif_get_string", referenced from:
      _argon2_verify_nif in argon2_nif-16ff57.o
  "_enif_get_uint", referenced from:
      _argon2_hash_nif in argon2_nif-16ff57.o
      _argon2_verify_nif in argon2_nif-16ff57.o
      _argon2_encodedlen_nif in argon2_nif-16ff57.o
  "_enif_inspect_binary", referenced from:
      _argon2_hash_nif in argon2_nif-16ff57.o
      _argon2_verify_nif in argon2_nif-16ff57.o
  "_enif_make_badarg", referenced from:
      _argon2_hash_nif in argon2_nif-16ff57.o
      _argon2_verify_nif in argon2_nif-16ff57.o
      _argon2_error_nif in argon2_nif-16ff57.o
      _argon2_encodedlen_nif in argon2_nif-16ff57.o
  "_enif_make_int", referenced from:
      _argon2_hash_nif in argon2_nif-16ff57.o
      _argon2_verify_nif in argon2_nif-16ff57.o
      _argon2_encodedlen_nif in argon2_nif-16ff57.o
  "_enif_make_string", referenced from:
      _argon2_hash_nif in argon2_nif-16ff57.o
      _argon2_error_nif in argon2_nif-16ff57.o
  "_enif_make_tuple", referenced from:
      _argon2_hash_nif in argon2_nif-16ff57.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [priv/argon2_nif.dylib] Error 1
```

**Comment by riverrun** [comment]
I'll look into it further and get back to you in a day or two.

**Comment by riverrun** [comment]
I've added an extra compile option for OS X. It's available from hex as version 0.11.2.
If that doesn't work, could you tell me if there is a `erl_nif.h` file in the `/usr/local/Cellar/erlang/19.1/lib/erlang/erts-8.1/include` directory?

**Comment by oscar-lopez** [comment]
Thanks for your time! yes, there's a filed called `erl_nif.h` in that directory. The project now compiles, but fails at runtime. For example, if I run this:

    Argon2.verify_hash("valid argon2 hash", "corresponding plain-text password")

I get these error messages:

```elixir
The on_load function for module Elixir.Argon2.Base returned {:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen(/<path-to-my-project>/_build/test/lib/argon2_elixir/priv/argon2_nif.so, 2): image not found\''}}

(UndefinedFunctionError) function Argon2.Base.verify_nif/3 is undefined (module Argon2.Base is not available)
```

**Comment by riverrun** [comment]
Great! There's some progress.
In the Makefile, change the `LIB_EXT := dylib` line to be `LIB_EXT := so` and try compiling again.
Then, try removing ` -install_name @rpath/lib$(LIB_NAME).$(LIB_EXT)` at the end of line 63 - I don't think we need this.
Thanks for your help with testing on OS X.

**Comment by oscar-lopez** [comment]
Yes! I did all of the above and now it finally works :) . The only extra step I had to do was recompiling Erlang to support dirty schedulers. Thank you very much!
