### ISSUE TITLE
CI: (Mix) Unpacking tarball failed: inner tarball error, no such file or directory

### ISSUE THREAD

**Issue by lpender** [riverrun/argon2_elixir#42]
Using: [buddy.works](https://buddy.works)
Docker Image: [cimg/elixir/1.11.0-browsers](https://hub.docker.com/layers/cimg/elixir/1.11.0-browsers/images/sha256-e905baecd393390f2d4ee837ab2c331588d8e31f02f73f0cd7bc015357b84ecc?context=explore)

After running `mix deps.get` I see the following error:

```
* Getting argon2_elixir (Hex package)
** (Mix) Unpacking tarball failed: inner tarball error, no such file or directory
```

![image](https://user-images.githubusercontent.com/1406554/100960077-6c52aa00-34d4-11eb-8f38-82eef91009c7.png)

Tried with a few different Elixir images

**Comment by riverrun** [comment]
Thanks for reporting the issue and sorry I haven't got back to you earlier.

First of all, have you been able to fix the issue?

If not, here are a couple of links with advice about the 'Unpacking tarball failed' error:
https://stackoverflow.com/questions/47991388/unpacking-inner-tarball-failed-invalid-argument
https://github.com/hexpm/hex/issues/716

Let me know how you get on and please let me know if any changes need to be made to argon2_elixir or the documentation.

**Comment by sandpipersburg** [comment]
Workaround/fix for this:
```
USER root
RUN mkdir _build deps \
&& chown $CI_USER:$CI_USER _build deps \
&& chmod 777 _build deps
```
A similar issue with yarn install:
https://github.com/yarnpkg/yarn/issues/1806

**Comment by kamaroly** [comment]
I run into the same issue on windows. All I had to do is **Run the same command (`mix deps.get`) as administrator**. 

**Below is the error I was getting**
![image](https://user-images.githubusercontent.com/3633772/215346078-61f96b4d-64be-489f-b836-32a48ee39962.png)

**Steps:**
1. Run `cmd.exe` as windows **administrator**
![image](https://user-images.githubusercontent.com/3633772/215346204-30d5bc65-fa0c-46c2-994f-50efef4355c3.png)

2. Navigated to the phoenix installation folder and rerun the same command, Boom! It worked
![image](https://user-images.githubusercontent.com/3633772/215346242-ba5e8c05-9ba4-4d08-9b0d-bcfd4ba6ac98.png)

**Comment by riverrun** [comment]
Closing this issue. If anyone feels like reopening, please let me know.
