### ISSUE TITLE
function Argon2.Base.hash_password/3 is undefined (module Argon2.Base is not available)

### ISSUE THREAD

**Issue by alexdang1993374** [riverrun/argon2_elixir#45]
Getting this error when trying to run this function `Argon2.hash_pwd_salt(secret)`
```sh
Process #PID<0.1451.0> raised an exception
** (RuntimeError) An error occurred when loading Argon2.
Make sure you have a C compiler and Erlang 20 installed.
If you are not using Erlang 20, either upgrade to Erlang 20 or
use bcrypt_elixir (version 0.12) or pbkdf2_elixir.
See the Comeonin wiki for more information.
```

**Comment by riverrun** [comment]
Could you let me know what OS you are using and what versions of Elixir, Erlang and argon2_elixir you are using?

**Comment by alexdang1993374** [comment]
OS: Windows10,
```
Erlang/OTP 23 [erts-11.1.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1]

Elixir 1.11.3 (compiled with Erlang/OTP 21)
```
argon2_elixir: 2.4.0

**Comment by riverrun** [comment]
For Windows, please check the [Requirements page](https://github.com/riverrun/comeonin/wiki/Requirements) in the Comeonin wiki, especially the instructions regarding running the `vsdevcmd` or `vcvarsall.bat` command. If that does not work, I recommend that you try asking about this on the [elixir forum](https://elixirforum.com/), as there might be some other Windows users there that could help you.

**Comment by alexdang1993374** [comment]
Thanks!
