### ISSUE TITLE
Support musl for Alpine environment

### ISSUE THREAD

**Issue by msudgh** [riverrun/argon2_elixir#47]
I'm already trying to use elixir:1.11.4-alpine but agron2 couldn't be compiled.

Logs:
```bash
could not compile dependency :argon2_elixir, "mix compile" failed. You can recompile this dependency with "mix deps.compile argon2_elixir", update it with "mix deps.update argon2_elixir" or clean it with "mix deps.clean argon2_elixir"
** (Mix) "make" not found in the path. If you have set the MAKE environment variable,
please make sure it is correct.
```

Make tool is not included in Alpine images cause of their nature, It would be useful if argon supports other build tools.

**Comment by riverrun** [comment]
I think you might get more help if you ask at [elixir forum](https://elixirforum.com/), where you might get some help with the setup.

**Comment by msudgh** [comment]
I thought its `argon2` compilation problem. I revised how the container was scaffolded and decided to follow another approach. All works fine.
Thanks, I close this issue.

**Comment by riverrun** [comment]
Great! Glad to hear you got it working.

**Comment by ybycode** [comment]
I'm facing the same issue, where I can't compile from a docker image based on Alpine Linux. Would you mind sharing how you managed @msudgh?
