### ISSUE TITLE
Compiling for Apple Silicon

### ISSUE THREAD

**Issue by JoshuaZacek** [riverrun/argon2_elixir#52]
OS: macOS Monterey 12.1 running on M1 Pro
Elixir & Erlang/OTP versions:

- Erlang/OTP 24 [erts-12.2] [source] [64-bit]
- Elixir 1.13.1 (compiled with Erlang/OTP 24)

As of now, argon2_elixir still compiles Intel binaries, even on an Apple Silicon machine, causing the entire module to break.

**Comment by JoshuaZacek** [comment]
Temporary fix:

1. Run `gcc --version` and copy the target
2. Open `/deps/argon2_elixer/Makefile` and insert this line: CFLAGS += -target (insert your target here)
3. Open `mix.exs` and change `{:argon2_elixir: "~> 2.0"}` to `{:argon2_elixir, path: "deps/argon2_elixir"}`
4. Delete `_build/dev/lib/argon2_elixir/priv/` and recompile

**Comment by riverrun** [comment]
Sorry for the delay in getting back to you.

Could you ask about this on [elixir forum](https://elixirforum.com/)? There might be other users with the same architecture who can help you.

And if anything needs to be updated in the library, please let me know.

**Comment by JoshuaZacek** [comment]
Hi,

I did make a post about this on the Elixir Forum.

However, this is when I was stupid. It turns out than an IDE extension was compiling the modules automatically, and it was running under Rosetta.

Thanks for responding though, and sorry for the issue.
