### ISSUE TITLE
Update the default configuration values in line with RFC 9106

### ISSUE THREAD

**Issue by riverrun** [riverrun/argon2_elixir#57]
Update the default configuration values (t_cost, parallelism and m_cost) in line with [RFC 9106](https://datatracker.ietf.org/doc/html/rfc9106#name-parameter-choice).

This proposal is to use the values outlined in the SECOND RECOMMENDED option (for cases where less memory is available), that is:

* t_cost: 3
* parallelism: 4
* m_cost: 16 (64 MiB of RAM)

The changes needed to the current config is to decrease the t_cost from 8 to 3 and increase the parallelism from 2 to 4.

**Comment by riverrun** [comment]
Fixed in v4.0.0

**Comment by wmnnd** [comment]
Since these factors are encoded in the hash, it's not necessary to adjust anything in the config for hashes that were generated with a previous version to continue to work, right?

**Comment by riverrun** [comment]
These changes are just for the default values when creating hashes. It does not affect verification in any way.

As you say, these values are encoded in the password hash, and the function will use the values in the hash to verify it.
