### ISSUE TITLE
Warning when compilng

### ISSUE THREAD

**Issue by ndrean** [riverrun/argon2_elixir#61]
I have this warning, several times when compiling. The code however works  (I use it embedded in Cloak).

```elixir
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option
```

**Comment by riverrun** [comment]
Apologies for not responding earlier - difficult to find time for open-source work. The warning you are seeing is harmless - it is just saying that the compiler does not know about that option. It does not affect the compilation.
