### ISSUE TITLE
Windows: Include paths not set correctly

### ISSUE THREAD

**Issue by cmcclellen** [riverrun/argon2_elixir#7]
For building the argon/argon2_nif, the include paths generated to not include argon2/src nor argon2/include when using Visual Studio 2015 command line compilers.

**Comment by riverrun** [comment]
Thanks for letting me know. I've just updated the Makefile for Windows, but I haven't been able to test it yet. Could you test version 1.2.1 and let me know if it works?

**Comment by cmcclellen** [comment]
Grabbed 1.2.2, and the path issue seems fixed -- thanks!
