### ISSUE TITLE
:nif_library_not_loaded

### ISSUE THREAD

**Issue by Sly777** [riverrun/argon2_elixir#9]
When I try to create a new user, I'm getting ```:nif_library_not_loaded``` error all the time. I have no idea why I'm getting this. It doesn't have any tricky way. I'm just trying to create password hash. You can see example below.

**Elixir v.**: 1.5.1
**Erlang v.**: 20.0.4
**Mac v.**: El capitan

```elixir
{:comeonin, "~> 4.0"},
{:argon2_elixir, "~> 1.2"}
```

```elixir
defmodule Helloworld.UserController do
  .....

  def login(conn, %{"username" => username, "password" => password}) do
    case Accounts.get_user_by_email(username) do
      nil ->
        case Accounts.create_user(%{"email": username, "password": password}) do
          nil ->
            IO.puts('no')
          user ->
            IO.puts('yes')
        end
      user ->
        IO.puts(user)
    end
  end

  .....

end
```

```elixir
defmodule Helloworld.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset

  alias Helloworld.Accounts.User

  @derive {
    Poison.Encoder,
    except: [:__meta__, :updated_at, :inserted_at]
  }

  schema "users" do
    field :email, :string
    field :password_hash, :string

    field :password, :string, virtual: true

    timestamps()
  end

  @doc false
  def changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:email, :password])
    |> validate_required([:email, :password])
    |> validate_length(:email, min: 1, max: 255)
    |> validate_format(:email, ~r/@/)
    |> hash_password()
    |> unique_constraint(:email)
  end

  defp hash_password(%{valid?: false} = changeset), do: changeset
  defp hash_password(%{valid?: true} = changeset) do
    hashed_password =
      changeset
      |> get_field(:password)
      |> Comeonin.Argon2.hashpwsalt()

    changeset
    |> put_change(:password_hash, hashed_password)
  end
end
```

**Comment by riverrun** [comment]
Could you show me the actual error please?

**Comment by riverrun** [comment]
You could also try running `(cd deps/argon2_elixir && make clean && make)` and see if that helps.

**Comment by Sly777** [comment]
Hi @riverrun, Sorry for replying late. I tried to run ```(cd deps/argon2_elixir && make clean && make)``` and it works! Thanks for your help. But why has it happened? What should I do for next projects?

**Comment by Sly777** [comment]
Btw I realised It's happening when I try debugging on ```IntelliJ IDEA CE``` with IntelliJ Elixir plugin. When I just run, It doesn't get any problem.

**Comment by riverrun** [comment]
Running `make clean` removes the old argon2 binary and forces a rebuild. This is not normally needed, but as you noticed, it is needed when you run your debugging tool. It is also sometimes needed after updating Erlang / Elixir to a new version.

I have considered changing the Makefile so that the argon2 binary is rebuilt every time you run `mix compile` or `mix  test`, and in fact the Windows version does do that, but that introduces extra overhead, and if you are running a lot of tests, it will slow them down.

I hope that answers your question.
